Opaque Typedefs: arr::test::evaluator Struct Reference
arr::test::evaluator Struct Reference
Unit Test Library
Check Evaluator
#include <evaluator.hpp>
Public Member Functions
evaluator (result_reporter &reporter, result_counter &counter, test_context &context) noexcept
void operator() (source_point sp) noexcept
Update the context of the test.
framer< test_context > call_frame (source_point sp)
Create a framer.
template<typename A >
void check (const A &actual) noexcept
Check whether the argument is true.
template<typename E , typename A >
void equal (const E &expected, const A &actual) noexcept
Check whether two values are equal according to operator==.
template<typename Eiter , typename Aiter , typename Count >
void range_equal (Eiter expected, Aiter actual, Count count) noexcept
Check whether two iterator ranges are equal according to operator==.
template<typename E , typename A , typename T >
void close (const E &expected, const A &actual, const T &tolerance) noexcept
Check whether two values are close according to operator<.
void strings (const char *expected, const char *actual) noexcept
Check whether two C-style strings have the same content
template<typename Rep , typename Period >
void time (const std::chrono::duration< Rep, Period > &limit)
Check whether the elapsed time of the test is less than the given limit.
void raised (const char *type_name)
Record that an exception was raised properly.
void unraised (const char *type_name)
Record that an exception should have been raised, but was not.
Private Attributes
decltype(std::chrono::high_resolution_clock::now()) const begin
Time at the beginning of the test.
result_reporter & _reporter
Reporter to create messages about the execution of the test.
result_counter & _counter
Accumulated results of the test's checks.
test_context & _context
Current context within the test.
Detailed Description
Check Evaluator
A test contains a sequence of checks. The check evaluator performs those checks and records their results. A check evaluator object is a parameter of every test.
Member Function Documentation
strings()
void arr::test::evaluator::strings (const char * expected, const char * actual) inline noexcept
Check whether two C-style strings have the same content
Note that evaluator::equal will compare the raw pointer values.
References _context, _counter, _reporter, arr::test::result_reporter::failed(), arr::test::result_counter::inc_failed(), arr::test::result_counter::inc_passed(), and arr::test::result_reporter::passed().
The documentation for this struct was generated from the following file:
include/arrtest/evaluator.hpp