Opaque Typedefs: arr::test::tests Struct Reference
arr::test::tests Struct Reference
Unit Test Library
Test list
#include <tests.hpp>
Static Public Member Functions
static void enlist (test *instance)
Add a test to the test list
static result_counter run_test (result_reporter &r, test *instance)
Run a test and report its results
static int run (result_reporter &reporter)
Run the entire test list
static int run ()
Run the entire test list, reporting to std::cout
Static Public Attributes
static std::vector< test * > test_list
The test list.
Detailed Description
Test list
Member Function Documentation
run() [1/2]
static int arr::test::tests::run (result_reporter & reporter) inline static
Run the entire test list
Parameters
reporter The result_reporter to give results to
Returns
EXIT_SUCCESS or EXIT_FAILURE, suitable to return from main
References arr::test::result_counter::inc_failed(), arr::test::result_counter::inc_passed(), arr::test::result_reporter::report_full(), run_test(), arr::test::result_counter::successful(), and test_list.
run() [2/2]
static int arr::test::tests::run () inline static
Run the entire test list, reporting to std::cout
Returns
EXIT_SUCCESS or EXIT_FAILURE, suitable to return from main
The documentation for this struct was generated from the following file:
include/arrtest/tests.hpp